POST http://localhost:3000/api/addPalet
Content-Type: application/json

{
    "date": "2023-09-06",
    "farmer": "Tsuberi",
    "variety": "Sheli",
    "size": 21,
    "cartonCount": 120,
    "weight": 587
}
####

POST http://localhost:3000/api/getPalet
Content-Type: application/json

{
    "farmer": "Tsuberi",
    "weighUnder": 700
}