POST https://tsuberi.com/api/addPalet
Content-Type: application/json

{
    "_id" : 1,
    "date": "2023-09-06",
    "farmer": "Tsuberi",
    "variety": "Tomi",
    "size": 18,
    "cartonCount": 120
    
}
####

POST https://tsuberi.com//api/getPalet
Content-Type: application/json

{
    "farmer": "Tsuberi"
    
}